# Time-Lag Feature Engineering for Regime Prediction

Decide to create two prediction variables, short-term: $y_{t+5}$, and medium/long-term: $y_{t+20}$. 

In our dataset, we have the following mapping of segments to regimes:
- **Segment 0** := BEAR
- **Segment 1** := BULL

In [21]:
# Load the data
import pandas as pd
FILE_PATH = r'C:\Users\jacob\Documents\GitHub\COMP0047-Data-Science-Project\notebooks\data\labeled_dataset.csv'
df = pd.read_csv(FILE_PATH)
df.drop(columns=['segment'], inplace=True)
df.head()

,Date,GSPC,VIX,SPY Volume,GDP,Core_Inflation,Unemployment,M2,Return,Return_5d,...,quarter,GDP_YoY,month,Core_Inflation_YoY,M2_YoY,Peak,Drawdown,VIX_Change,VIX_Change_5d,regime
0,1994-01-27,477.049988,10.30,344500,10939.116,66.902,6.6,3474.9,0.008136,0.004358,...,1,0.034307,1,0.022466,0.016320,477.049988,0.000000,-0.870000,-0.860000,bear
1,1994-01-28,478.700012,9.94,356500,10939.116,66.902,6.6,3474.9,0.003459,0.008384,...,1,0.034307,1,0.020516,0.017689,478.700012,0.000000,-0.360001,-1.150001,bear
2,1994-01-31,481.609985,10.63,313800,10939.116,66.902,6.6,3474.9,0.006079,0.020425,...,1,0.034307,1,0.020516,0.017689,481.609985,0.000000,0.690001,-0.970000,bear
3,1994-02-01,479.619995,10.65,303600,10939.116,67.047,6.6,3475.7,-0.004132,0.018474,...,1,0.034307,2,0.022728,0.017924,481.609985,-0.004132,0.020000,-0.730000,bear
4,1994-02-02,482.000000,10.61,307600,10939.116,67.047,6.6,3475.7,0.004962,0.018597,...,1,0.034307,2,0.022728,0.017924,482.000000,0.000000,-0.040000,-0.560000,bear

In [23]:
# Map regime to binary values
regime_mapping = {'bull': 1, 'bear': 0}
df['target'] = df['regime'].map(regime_mapping)
df['target'].value_counts()

target
1    5061
0    3005
Name: count, dtype: int64

In [27]:
h_long = 20
h_short = 5

# Shift the prediction variables
df['target_long'] = df['target'].shift(-h_long)
df['target_short'] = df['target'].shift(-h_short)
df.head()

,Date,GSPC,VIX,SPY Volume,GDP,Core_Inflation,Unemployment,M2,Return,Return_5d,...,Core_Inflation_YoY,M2_YoY,Peak,Drawdown,VIX_Change,VIX_Change_5d,regime,target,target_long,target_short
0,1994-01-27,477.049988,10.30,344500,10939.116,66.902,6.6,3474.9,0.008136,0.004358,...,0.022466,0.016320,477.049988,0.000000,-0.870000,-0.860000,bear,0,0.0,0.0
1,1994-01-28,478.700012,9.94,356500,10939.116,66.902,6.6,3474.9,0.003459,0.008384,...,0.020516,0.017689,478.700012,0.000000,-0.360001,-1.150001,bear,0,0.0,0.0
2,1994-01-31,481.609985,10.63,313800,10939.116,66.902,6.6,3474.9,0.006079,0.020425,...,0.020516,0.017689,481.609985,0.000000,0.690001,-0.970000,bear,0,0.0,0.0
3,1994-02-01,479.619995,10.65,303600,10939.116,67.047,6.6,3475.7,-0.004132,0.018474,...,0.022728,0.017924,481.609985,-0.004132,0.020000,-0.730000,bear,0,0.0,0.0
4,1994-02-02,482.000000,10.61,307600,10939.116,67.047,6.6,3475.7,0.004962,0.018597,...,0.022728,0.017924,482.000000,0.000000,-0.040000,-0.560000,bear,0,0.0,0.0

In [29]:
# Drop rows with NaN values in the target columns
df.dropna(subset=['target_long', 'target_short'], inplace=True)
df.isna().sum()

Date                  0
GSPC                  0
VIX                   0
SPY Volume            0
GDP                   0
Core_Inflation        0
Unemployment          0
M2                    0
Return                0
Return_5d             0
Return_20d            0
Return_Smooth         0
RSI_14                0
MACD_Line             0
MACD_Signal           0
MACD_Hist             0
year                  0
quarter               0
GDP_YoY               0
month                 0
Core_Inflation_YoY    0
M2_YoY                0
Peak                  0
Drawdown              0
VIX_Change            0
VIX_Change_5d         0
regime                0
target                0
target_long           0
target_short          0
dtype: int64